server:
  port: 8086

logging:
  level:
    com.truextend.dev.recipes: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file: Logs/debug.log

spring:
   config:
      name:  recipes
   application:
      name:  recipes
   jpa:
      show-sql: true